colciencias/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from colciencias.views import *

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'proyecto.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

   
    url(r'^admin/', include(admin.site.urls)),
    url(r'^estado/','colciencias.views.busqueda', name= estado),
    url(r'^verificarTransferencias/','colciencias.views.verificarTransferencias', name= transferencias),
    url(r'^CDR/$', 'colciencias.views.cdr'),
    url(r'^inicio/$', 'colciencias.views.inicio'),
 	url(r'^Registros/$', 'colciencias.views.Consultacdr'),

)

proyecto/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from colciencias.views import *

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'proyecto.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

   
    url(r'^admin/', include(admin.site.urls)),
    url(r'^estado/$', busqueda),
    url(r'^verificarTransferencias/$',verificarTransferencias),
 	url(r'^CDR/$', 'colciencias.views.cdr', name='CDR'),
 	#url(r'^Registros/$', 'colciencias.views.Consultacdr'), 
 	#url(r'^inicio/$', 'colciencias.views.inicio'),  	
 	url(r'^$', 'colciencias.views.inicio', name='home'),
 	url(r'^add/$', formulario, name='add'),
 	url(r'^cargar/$', formularioPro, name='proforma'),
 	url(r'^expedir/$', expedir_cdr, name='expedir'),
 	url(r'^crearConvenio/$', 'colciencias.views.gestionarConvenioEnSolicitud'),
 	url(r'^actualizarDatos/$', 'colciencias.views.gestionarConvenioRegistro'),
 	url(r'^anexo/$', formularioAnexo, name='anexo'),
 	url(r'^programarDesembolso/$', programarDesembolso, name='desembolso'),

)

colciencias/models.py
from django.db import models

class ProyectoInversion(models.Model):
    ID = models.CharField(max_length=20 , primary_key=True)
    recursos = models.CharField(max_length=100)
    metas = models.TextField()
    vigencia = models.CharField(max_length=10)
    #def __init__(self):
        #super(proyectoInversion, self).__init__()
        #
#Esta clase
class TransferenciasSiif(models.Model):
    ID = models.CharField(max_length=30 , primary_key=True)
    convenio = models.CharField(max_length=30)
    fecha = models.DateField()
    valorTransferencia = models.FloatField()
    autoridad = models.CharField(max_length=30)
    entidad = models.CharField(max_length=30)
     #def __init__(self):
        #super(siif, self).__init__()
        #

class ProgramacionPago(models.Model):
    ID = models.CharField(max_length=30 , primary_key=True)
    convenio = models.CharField(max_length=30)
    fecha = models.DateField()
    valorTransferencia = models.FloatField()
    autoridad = models.CharField(max_length=30)
    entidad = models.CharField(max_length=30)
     #def __init__(self):
        #super(siif, self).__init__()
        #

class Convenio(models.Model):
    numConvenio = models.CharField(max_length=30 , primary_key=True)
    nombre = models.CharField(max_length=50)
    tipoConvenio = models.CharField(max_length=30)
    valorTotal = models.FloatField()
    RP = models.CharField(max_length=50)
    proyectoInversion_FK = models.ForeignKey(ProyectoInversion)
    fechaInicio = models.DateField()
    fechaSuscripcion = models.DateField()
    fechaLegalizacion = models.DateField()
    fechaFInalizacion = models.DateField()
    areaResponsable = models.CharField(max_length=30)
    supervisor = models.CharField(max_length=100)
    plazo = models.DateField()
    objeto = models.CharField(max_length=100)
    #def __init__(self):
        #super(Convenio, self).__init__()
        #

    def __str__(self):
        return self.nombre

class Organizacion(models.Model):
    ID = models.CharField(max_length=20 , primary_key=True)
    nombre = models.CharField(max_length=100)
    NIT = models .CharField(max_length=20)
    convenio_FK = models.ForeignKey(Convenio)
    valor = models.FloatField()

    def __str__(self):
        return self.nombre
    #def __init__(self):
        #super(organizacion, self).__init__()
        #

class Aporte(models.Model):
    ID = models.CharField(max_length=30 , primary_key=True)
    fecha = models.DateField()
    valor = models.FloatField()
    validado = models.CharField(max_length=10)
    esProgramado = models.CharField(max_length=10)
    organizacion_FK = models.ForeignKey(Organizacion , null=True)
    convenio_FK = models.ForeignKey(Convenio)
    #def __init__(self):
        #super(Aporte, self).__init__()
        #

class Becario(models.Model):
    ID = models.CharField(max_length=30 , primary_key=True)
    nombre = models.CharField(max_length=100)
    codigo = models.CharField(max_length=30)
    cumpleRequisitos = models.CharField(max_length=10)
    informacionBecario = models.TextField()
    informacionTesis = models.TextField()
    convenio_FK = models.ForeignKey(Convenio)
    #def __init__(self):
        #super(Becario, self).__init__()
        #

class Seguimiento(models.Model):
    ID = models.OneToOneField(Becario, primary_key=True)
    fecha = models.DateField()
    semestre = models.IntegerField()
    valorMatricula = models.FloatField()
    NumMatriculasAprobadas = models.IntegerField()
    #def __init__(self):
        #super(Seguimiento, self).__init__()
        #

class Desembolso(models.Model):
    ID = models.CharField(max_length=30 , primary_key=True)
    fechaSolicitud = models.DateField()
    valor = models.FloatField()
    girado = models.CharField(max_length=100)
    fechaGiro = models.DateField()
    condiciones = models.TextField()
    organizacion_FK = models.ForeignKey(Organizacion , null=True)
    becario_FK = models.ForeignKey(Becario)
    #def __init__(self):
        #super(Desembolso, self).__init__()
        #

class Proyecto(models.Model):
    ID = models.CharField(max_length=30 , primary_key=True)
    duracion = models.FloatField()
    lineaTematica = models.CharField(max_length=50)
    lugarEjecucion = models.CharField(max_length=50)
    titulo = models.CharField(max_length=100)
    CDR = models.CharField(max_length=50)
    estado = models.CharField(max_length=20)
    justificacionEstado = models.TextField()
    convenio_FK = models.ForeignKey(Convenio)
    desembolso_FK = models.ForeignKey(Desembolso)
    #def __init__(self):
        #super(Proyecto, self).__init__()
        #

class Novedad(models.Model):
    ID = models.CharField(max_length=30 , primary_key=True)
    tipoNovedad = models.CharField(max_length=20)
    estado = models.CharField(max_length=20)
    convenio_FK = models.ForeignKey(Convenio , null=True)
    proyecto_FK = models.ForeignKey(Proyecto , null=True)
    #def __init__(self):
        #super(Novedad, self).__init__()
        #

class Anexo(models.Model):
    ID = models.CharField(max_length=30 , primary_key=True)
    fechaCargue = models.DateField()
    descripcion = models.TextField()
    archivo = models.FileField()
    desembolso_FK = models.ForeignKey(Desembolso , null=True)
    convenio_FK = models.ForeignKey(Convenio , null=True)
    proyecto_FK = models.ForeignKey(Proyecto , null=True)
    #def __init__(self):
        #super(Anexo, self).__init__()
        #

class Proforma(models.Model):
    ID = models.CharField(max_length=30 , primary_key=True)
    fechaCargue = models.DateField()
    descripcion = models.TextField()
    archivo = models.FileField()
    
    def __str__(self):
        return self.ID

    #valida = models.BooleanField(default=True)
class CDR(models.Model):
    ID = models.CharField(max_length=30 , primary_key=True) 
    Convenio = models.ForeignKey(Convenio , null=True)
    Proforma = models.ForeignKey(Proforma , null=True)
    validado = models.BooleanField(default=True)
    organizacion = models.ForeignKey(Organizacion, null=True)

    def __str__(self):
        return self.ID

class Notificacion(models.Model):
    ID = models.CharField(max_length=30 , primary_key=True)
    #def __init__(self):
        #super(Notificacion, self).__init__()
        #

class Notificacion_Proyecto(models.Model):
    ID = models.CharField(max_length=30 , primary_key=True)
    destinatario = models.CharField(max_length=30)
    mensaje = models.TextField()
    notificacion_FK = models.ForeignKey(Notificacion)
    proyecto_FK = models.ForeignKey(Proyecto)
    #def __init__(self):
        #super(Notificacion_Proyecto, self).__init__()
        #

class Notificacion_Convenio(models.Model):
    ID = models.CharField(max_length=30 , primary_key=True)
    destinatario = models.CharField(max_length=30)
    mensaje = models.TextField()
    notificacion_FK = models.ForeignKey(Notificacion)
    convenio_FK = models.ForeignKey(Convenio)
    #def __init__(self):
        #super(Notificacion_Proyecto, self).__init__()
        #
class Estado(models.Model):
    ID = models.CharField(max_length=30 , primary_key=True)
    convenio = models.CharField(max_length=30) 
    transferido = models.FloatField()
    transferir = models.FloatField()
    pagados = models.FloatField()
    noComprometidos = models.FloatField()
    noGirados = models.FloatField()
    comprometidos = models.FloatField()
    comprometer = models.FloatField()
    porPagar = models.FloatField()
    transferidoColciencias = models.FloatField()
    transferirColciencias = models.FloatField()
    transferidoOtrasEntidades = models.FloatField()
    girosOtrasEntidades = models.FloatField()
    #def __init__(self):
        #super(estado, self).__init__()
        #

class ConvenioSol(models.Model):
    numConvenio = models.CharField(max_length=30 , primary_key=True)
    nombre = models.CharField(max_length=50)
    tipoConvenio = models.CharField(max_length=30)
    estado = models.CharField(max_length=30)
    valorTotal = models.FloatField()
    RP = models.CharField(max_length=50)
    fechaInicio = models.DateField(null=True)
    fechaSuscripcion = models.DateField(null=True)
    fechaLegalizacion = models.DateField(null=True)
    fechaFInalizacion = models.DateField(null=True)
    areaResponsable = models.CharField(max_length=30)
    supervisor = models.CharField(max_length=100)
    plazo = models.DateField(null=True)
    objeto = models.CharField(max_length=100)

class Ffjc(models.Model):
    ID = models.CharField(max_length=30, primary_key=True)
    fecha = models.DateField(null=True)
    valor = models.FloatField()
    pdf = models.FileField()

class Giro(models.Model):
    ID = models.CharField(max_length=30,primary_key=True)
    num = models.CharField(max_length=30)
    fecha = models.DateField(null=True)
    numSol = models.CharField(max_length=30)
    valor = models.FloatField()

class propuesta(models.Model):
    ID = models.CharField(max_length=20 , primary_key=True)
    nombre = models.CharField(max_length=100)
    fecha = models.DateField()
    desembolso_FK= models.ForeignKey(Desembolso, null=True)

    def __str__(self):
        return self.nombre

class Convocatoria(models.Model):
    ID = models.CharField(max_length=20 , primary_key=True)
    nombre = models.CharField(max_length=100)
    fecha = models .DateField()
    convenio_FK = models.ForeignKey(Convenio, null=True)
    propuesta_FK= models.ForeignKey(propuesta, null=True)
    validado = models.BooleanField(default=True)

colciencias/forms.py
#
from django import forms
from django.forms import ModelForm
from colciencias.models import *	

class UploadFileForm(forms.Form):
    title = forms.CharField(max_length=50)
    file = forms.FileField()


class OrganizacionForm(ModelForm):
    class Meta:
        model = Organizacion
      	convenio='convenio_FK'
        fields = ('ID','nombre', 'NIT', convenio, 'valor')
      #  exclude = ["numConvenio", "nombre","tipoConvenio", "RP", "proyectoInversion_FK" , "fechaInicio", "fechaSuscripcion", "fechaLegalizacion", "fechaFInalizacion","areaResponsable","supervisor","plazo", "objeto"]



class ProformaForm(ModelForm):
    class Meta:
        model = Proforma
        fields =  ('ID','fechaCargue','descripcion','archivo')


class AnexoForm(ModelForm):
    class Meta:
        model = Anexo
        fields =  ('ID','fechaCargue','descripcion','archivo','convenio_FK')

colciencias/templates/gestionarRegistro.html
<!DOCTYPE html>
<html>
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Actualizar datos</title>

    <!-- Bootstrap Core CSS -->
    <link href="{{STATIC_URL}}css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{{STATIC_URL}}css/logo-nav.css" rel="stylesheet">

</head>
<body>
      <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
              
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand">
                    <img src="{{STATIC_URL}}img/logo.png" alt="logo"  width="180" height="50">
                </a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                     <li>
                        <a href="#">Inicio</a>
                    </li>
                     <li>
                        <a href="http://127.0.0.1:8000/estado/">Estado cuenta</a>
                    </li>
                    <li>
                        <a href="http://127.0.0.1:8000/CDR/">CDR</a>
                    </li>
                     <li>
                        <a href="http://127.0.0.1:8000/verificarTransferencias/">Verificar transferencias</a>
                    </li>
                    <li>
                        <a href="#">Otros</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
               
            </div>
        </div>
    </div>
    <!-- /.container -->

    <!-- jQuery Version 1.11.0 -->
    <script src="{{STATIC_URL}}js/jquery-1.11.0.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{{STATIC_URL}}js/bootstrap.min.js"></script>
    
        <h3>Estado del convenio: Registro</h3>
    
    <center>
    <div><form id='datos' action='' method='POST'>
                {% csrf_token %}
                {{form.as_p}}
                 <table style="width:500px;height:350px">
                    <tr>
                        <td>
                            <label><b>Número del convenio: </b></label>
                        </td>
                        <td>
                            <input type="text" size="15" maxlength="30" name="numCon" id="id_numCon" style="width:300px">
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <b>Objeto del convenio: </b>
                        </td>
                        <td>
                            <input type="text" size="15" maxlength="30" name="objeto" id="id_objeto" style="width:300px">
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <b>Valor del convenio: </b>
                        </td>
                        <td>
                            <input type="text" size="15" maxlength="30" name="valor" id="id_valor" style="width:300px">
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <b>Fecha de suscripción: </b>
                        </td>
                        <td>
                            <input type="date" name="fechaSus" style="width:300px">
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <b>Fecha de legalización: </b>
                        </td>
                        <td>
                            <input type="date" name="fechaLeg" style="width:300px">
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <b>Fecha de inicio: </b>
                        </td>
                        <td>
                            <input type="date" name="fechaIni" style="width:300px">
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <b>Fecha de finalización: </b>
                        </td>
                        <td>    
                            <input type="date" name="fechaFin" style="width:300px">
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <b>Plazo: </b>
                        </td>
                        <td>
                           <input type="text" size="15" maxlength="30" name="plazo" id="id_plazo" style="width:300px">
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <b>Área responsable: </b>
                        </td>
                        <td>    
                            <input type="text" size="15" maxlength="30" name="area" id="id_area" style="width:300px">
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <b>Supervisor: </b>
                        </td>
                        <td>
                            <input type="text" size="15" maxlength="30" name="supervisor" id="id_supervisor" style="width:300px">
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <b>PDF convenio de aportes: </b>
                        </td>
                        <td>
                            <input type="file" name="file" id="id_file" />
                        </td>
                    </tr>
                           
                </table>

    </div>
    </center>
    <div align="right">
    <input type= submit value="Registrar" name='boton' id="id_registrar">
</div>
<footer style="text-align:right">
        <center><h3><b>Sistema Integrado Colciencias - 2014</center></h3>
        </footer>
</body>
</html>

colciencias/templates/gestionarSolicitud.html
<!DOCTYPE html>
<html>
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Crear Convenio</title>

    <!-- Bootstrap Core CSS -->
    <link href="{{STATIC_URL}}css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{{STATIC_URL}}css/logo-nav.css" rel="stylesheet">




</head>
<body>
      <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
              
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand">
                    <img src="{{STATIC_URL}}img/logo.png" alt="logo"  width="180" height="50">
                </a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                     <li>
                        <a href="#">Inicio</a>
                    </li>
                     <li>
                        <a href="http://127.0.0.1:8000/estado/">Estado cuenta</a>
                    </li>
                    <li>
                        <a href="http://127.0.0.1:8000/CDR/">CDR</a>
                    </li>
                     <li>
                        <a href="http://127.0.0.1:8000/verificarTransferencias/">Verificar transferencias</a>
                    </li>
                    <li>
                        <a href="#">Otros</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
               
            </div>
        </div>
    </div>
    <!-- /.container -->

    <!-- jQuery Version 1.11.0 -->
    <script src="{{STATIC_URL}}js/jquery-1.11.0.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{{STATIC_URL}}js/bootstrap.min.js"></script>
    
        <h3>Estado del convenio: En solicitud</h3>
    
    <center>
    <div><form id='datos' action='' method='POST'>
                {% csrf_token %}
                {{form.as_p}}
                 <table style="width:600px;height:350px">
                    <tr>
                        <td>
                            <label><b>Seleccione fuente de recursos: </b></label>
                        </td>
                        <td>
                            <select name="tipo" id="id_seleccionar">
                                <option selected="selected" value="0">Seleccione recurso......</option>
                                <option value="colciencias" id="id_colciencias" name="colciencias">Recursos Colciencias
                                </option>
                                <option value="colciencias-sena" id="id-colsena" name="colciencias-sena">Recursos Colciencias - SENA</option>
                                <option value="propios" id="id_propios" name="propios">Recursos Propios de Otras Entidades
                                </option>
                                <option value="otras" id="id_otras" name="otras">Recursos Nación de Otras Entidades</option>
                                <option value="regalias" id="id_regalias" name="regalias">Recursos Regalías
                                </option>
                                <option value="bm" id="id_bm" name="bm">Recursos Colciencias -BM
                                </option>
                                <option value="bid" id="id_bid" name="bid">Recursos Colciencias –BID
                                </option>
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <b>Ingrese el numero de solicitud: </b>
                        </td>
                        <td>
                            <input type="text" size="15" maxlength="30" name="num" id="id_num" style="width:263px">
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <b>Fecha: </b>
                        </td>
                        <td>
                            <b><script type="text/javascript">
                            var d = new Date();
                            document.write(d.getDate()+'/'+(d.getMonth()+1)+'/'+d.getFullYear());
                            </script>
                            </b>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <b>Archivo PDF: </b>
                        </td>
                        <td>
                            <input type="file" name="file" id="id_file" />
                        </td>
                    <tr>
                        <td>
                            <b>Ingrese numero de organizaciones a asignar: </b>
                        </td>
                        <td>
                            <input type="text" size="15" maxlength="30" name="org" id="id_org" style="width:100px">
                            <input type= submit value="Aceptar" name='boton' id="id_aceptar">
                        </td>
                    </tr>
                    {% for dato in datos %}
                    <tr>
                        <td>
                            Organización {{dato}}: 
                        </td>
                        <td>
                            <input type="text" size="15" maxlength="30" name="numrp" id="id_numrp" style="width:263px">
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Valor:  
                        </td>
                        <td>
                            <input type="text" size="15" maxlength="30" name="numrp" id="id_numrp" style="width:263px">
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Fecha:  
                        </td>
                        <td>
                            <input type="date" name="fecha" style="width:263px">
                        </td>
                    </tr>
                    {% endfor %}
                    </tr>
                    <tr>
                        <td>
                            <b>Número del proyecto de inversión: </b>
                        </td>
                        <td>
                            <input type="text" size="15" maxlength="30" name="numInv" id="id_numrp" style="width:263px">
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <b>Año de vigencia de los recursos: </b>
                        </td>
                        <td>
                            <input type="text" size="15" maxlength="30" name="anio" id="id_numrp" style="width:263px">
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <b>Número RP: </b>
                        </td>
                        <td>    
                            <input type="text" size="15" maxlength="30" name="numrp" id="id_numrp" style="width:263px">
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <b>Fecha  RP: </b>
                        </td>
                        <td>
                           <input type="date" name="fechaRp" style="width:263px">
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <b>Valor toral del convenio: </b>
                        </td>
                        <td>    
                            <input type="text" size="15" maxlength="30" name="total" id="id_total" style="width:263px">
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <b>Valor discriminador por organización: </b>
                        </td>
                        <td>
                            <input type="text" size="15" maxlength="30" name="discri" id="id_discri" style="width:263px">
                        </td>
                    </tr>
                    <tr>
                        <td>

                        </td>
                        <td>
                            <input type= submit value="Registrar" name='boton' id="id_registrar">
                        </td>
                    </tr>
                 </table>

    </div>
    </center>
    <center>
        <h3>Programación de giros</h3>
        <table style="width:550px;height:270px">
            <tr>
                <td>
                    <b>Valor: </b>
                </td>
                <td>
                    <input type="text" size="15" maxlength="30" name="valor" id="id_valor" style="width:263px">
                </td>
            </tr>
            <tr>
                <td>
                    <b>Número de orden: </b>
                </td>
                <td>
                    <input type="text" size="15" maxlength="30" name="numOr" id="id_numOr" style="width:263px">
                </td>
            </tr>
            <tr>
                <td>
                    <b>Fecha: </b>
                </td>
                <td>
                    <input type="date" name="fechaGir" style="width:263px">
                </td>
            </tr>
            <tr>
                <td>
                    <b>Número de solicitud: </b>
                </td>
                <td>
                    <input type="text" size="15" maxlength="30" name="numSol" id="id_numSol" style="width:263px">
                </td>
            </tr>
            <tr>
                <td>
                    <select name="ffjc" id="id_ffjc">
                                <option selected="selected" value="0">No involucra aportes</option>
                                <option value="colciencias" id="id_colciencias" name="colciencias">Involucra aportes del FFJC</option>
                    </select>
                </td>
            </tr>
            <tr>
                <td>
                     
                </td>
                <td>
                    Diligenciar en caso de contar con aportes del FFJC
                </td>
            </tr>
            <tr>
                <td>
                    <b>Fecha recepción giro: </b>
                </td>
                <td>
                    <input type="date" name="fechaffjc" style="width:263px">
                </td>
            </tr>
            <tr>
                <td>
                    <b>Valor recibido: </b>
                </td>
                <td>
                    <input type="text" size="15" maxlength="30" name="valorRec" id="id_valorRec" style="width:263px">
                </td>
            </tr>
            <tr>
                <td>
                    <b>PDF soporte: </b>
                </td>
                <td>
                    <input type="file" name="filePdf" id="id_file" />
                </td>
            </tr>
            <tr>
                <td>

                </td>
                <td>
                    <input type= submit value="Guardar" name='boton' id="id_registrarDos">
                </td>
            </tr>
        </table>
    </center>
    <footer style="text-align:right">
        <center><h3><b>Sistema Integrado Colciencias - 2014</center></h3>
        </footer>

</body>
</html>